version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro   # Traefik krijgt info van Docker
      - ./traefik.yml:/etc/traefik/traefik.yml        # hoofdconfiguratie
      - ./letsencrypt/acme.json:/letsencrypt/acme.json                     # SSL cert storage
    restart: unless-stopped
    networks:
      - web

  website:
    image: nginx:alpine
    container_name: noeka-website
    volumes:
      - "./web:/usr/share/nginx/html"                # website bestanden
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # custom nginx config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`noeka.duckdns.org`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls.certresolver=letsencrypt"
      - "traefik.http.routers.website.tls=true"
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
